#!/usr/bin/env python3
"""
NBA TC Engine — Live Report Generator
Updated to match the latest roster data in nba_tc_engine_v8.py
"""
exec(open('nba_tc_engine_v8.py').read().split('if __name__')[0])

# ── INJURY OVERRIDES ─────────────────────────────────────────────────────────
# SAS = San Antonio Spurs (SA in TEAM_ROSTERS)
# OKC = Oklahoma City Thunder
# CLE = Cleveland Cavaliers
# NYK = New York Knicks
reset_injuries()
apply_injuries({
    "SAS": {"De'Aaron Fox": "QUESTIONABLE", "Luke Kornet": "QUESTIONABLE"},
    "OKC": {"Jalen Williams": "ACTIVE"},
    "NYK": {"Jalen Brunson": "QUESTIONABLE"},
})

OUT = []

def h1(text):
    OUT.append("\n## " + text + "\n")

def h2(text):
    OUT.append("\n### " + text + "\n")

def table_row(cells, header=False):
    OUT.append("| " + " | ".join(str(c) for c in cells) + " |")
    if header:
        OUT.append("| " + " | ".join(["---"] * len(cells)) + " |")

def p(text):
    OUT.append(text)

def divider():
    OUT.append("\n---\n")

# ── HEADER ───────────────────────────────────────────────────────────────────
p("# NBA TC Engine — Conference Finals Live Report")
p("**May 18, 2026** | Generated by TC Engine v8.0 | Live odds via FOX Sports")
p("")
divider()

# ── GAME 1: SAS @ OKC ────────────────────────────────────────────────────────
h1("🏀 Game 1: San Antonio Spurs @ Oklahoma City Thunder")
p("**West Conference Finals — Game 1**")
p("8:30 PM ET | NBC/Peacock | Paycom Center, OKC")
p("")
p("| **Line** | SAS +6.5 | OKC -6.5 | Total: 220.5 |")
p("|---|---|---|---|")

h2("Injury Status")
p("- De'Aaron Fox (SAS): ⚠️ Q — right ankle soreness, Game 1 status uncertain")
p("- Luke Kornet (SAS): ⚠️ Q — left foot soreness, first possible miss of playoffs")
p("- Jalen Williams (OKC): ✅ ACTIVE — returning after 6-game hamstring absence")
p("- SGA: ✅ 2026 MVP, no injury designation")
p("")

h2("TC Game Summary")
gl1 = game_line("SAS", "OKC", market_total=220.5)
table_row(["Metric", "Value"], header=True)
table_row(["TC Line", "**" + str(gl1["tc_line"]) + "**"])
table_row(["Market Total", "220.5"])
table_row(["Edge (vs Market)", str(gl1["edge"])])
table_row(["Signal", "**" + gl1["signal"] + "**"])
table_row(["SAS Starter TC", str(gl1["away_tc"])])
table_row(["OKC Starter TC", str(gl1["home_tc"])])
table_row(["Raw Combined (TC pts)", str(gl1["raw_combined"])])
table_row(["TC Final (x1.52)", str(round(gl1["tc_final"], 1))])
p("")

h2("TC System Summary — SAS @ OKC")
table_row(["Pick", "TC Line", "Market Total", "Edge", "Signal"], header=True)
sig1 = gl1["signal"]
pick1 = "UNDER" if sig1 == "UNDER" else "OVER"
table_row([pick1, str(gl1["tc_line"]), "220.5", str(gl1["edge"]), sig1])
p("")
p("**Note:** TC Line (205) is 15.5 points BELOW market total (220.5). " +
   "Market is pricing in a higher-scoring game than TC model projects. " +
   "Signal is UNDER — the market total is expensive on the OVER.")
p("")

def player_table(team_abbr, label, is_home=False):
    s = starters(team_abbr)
    home_away = "HOME" if is_home else "AWAY"
    h2(label + " [" + home_away + "]")
    table_row(["#", "Player", "Pos", "HT",
               "PTS", "REB", "AST", "3PM",
               "TC_PTS", "TC_REB", "TC_AST", "TC_3PM",
               "T-PTS", "Edge", "Conf", "Pick", "Status"], header=True)
    for i, pl in enumerate(s[:5], 1):
        tc = pl.tc_all()
        bl = pl.book_line()
        e = pl.edge()
        conf = pl.conf() * 100
        pick = "OVER" if e > 0 else "UNDER"
        flag = "⚠️ Q" if pl.status == "QUESTIONABLE" else ("❌ OUT" if pl.status == "OUT" else "✅")
        table_row([str(i), pl.name, pl.pos, pl.ht,
                   str(pl.pts), str(pl.reb), str(pl.ast), str(pl.tpm),
                   "**" + str(round(tc["pts"], 1)) + "**",
                   "**" + str(round(tc["reb"], 1)) + "**",
                   "**" + str(round(tc["ast"], 1)) + "**",
                   "**" + str(round(tc["3pm"], 1)) + "**",
                   str(bl), str(round(e, 1)), str(int(conf)) + "%", pick, flag])
    if len(s) > 5:
        table_row(["", "--- BENCH ---", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""])
        for pl in s[5:9]:
            tc = pl.tc_all()
            bl = pl.book_line()
            e = pl.edge()
            conf = pl.conf() * 100
            pick = "OVER" if e > 0 else "UNDER"
            table_row(["", pl.name, pl.pos, pl.ht,
                       str(pl.pts), str(pl.reb), str(pl.ast), str(pl.tpm),
                       "**" + str(round(tc["pts"], 1)) + "**",
                       "**" + str(round(tc["reb"], 1)) + "**",
                       "**" + str(round(tc["ast"], 1)) + "**",
                       "**" + str(round(tc["3pm"], 1)) + "**",
                       str(bl), str(round(e, 1)), str(int(conf)) + "%", pick, ""])
    p("")

player_table("SAS", "San Antonio Spurs", is_home=False)
player_table("OKC", "Oklahoma City Thunder", is_home=True)

h2("Top Edge Bets — SAS @ OKC (Player Props)")
for pl in sorted(starters("SAS"), key=lambda x: abs(x.edge()), reverse=True)[:8]:
    e = pl.edge()
    conf = pl.conf() * 100
    pick = "OVER" if e > 0 else "UNDER"
    qual = "✅" if abs(e) >= 2.5 else "  "
    p("- " + qual + " **" + pl.name + "** (" + pl.pos + ") — "
      "TC_PTS: " + str(round(pl.tc_pts(), 1)) + " | Book Line: " + str(pl.book_line()) +
      " | Edge: **" + str(round(e, 1)) + "** | Conf: " + str(int(conf)) + "% | Pick: **" + pick + "**")

p("")
for pl in sorted(starters("OKC"), key=lambda x: abs(x.edge()), reverse=True)[:8]:
    e = pl.edge()
    conf = pl.conf() * 100
    pick = "OVER" if e > 0 else "UNDER"
    qual = "✅" if abs(e) >= 2.5 else "  "
    p("- " + qual + " **" + pl.name + "** (" + pl.pos + ") — "
      "TC_PTS: " + str(round(pl.tc_pts(), 1)) + " | Book Line: " + str(pl.book_line()) +
      " | Edge: **" + str(round(e, 1)) + "** | Conf: " + str(int(conf)) + "% | Pick: **" + pick + "**")

# ── GAME 2: CLE @ NYK ────────────────────────────────────────────────────────
divider()
h1("🏀 Game 2: Cleveland Cavaliers @ New York Knicks")
p("**East Conference Finals — Game 1**")
p("May 19, 2026 | 8:00 PM ET | Madison Square Garden, New York")
p("")
p("| **Line** | CLE +7 | NYK -7 | Total: 220.5 |")
p("|---|---|---|---|")

h2("Injury Status")
p("- Jalen Brunson (NYK): ⚠️ Q — calf, limited in recent practice")
p("- Caris LeVert (CLE): ⚠️ Q — knee, uncertain for Game 1")
p("- Georges Niang (CLE): day-to-day")
p("- Jarrett Allen (CLE): ✅ ACTIVE")
p("- Donovan Mitchell (CLE): ✅ ACTIVE")
p("")

h2("TC Game Summary")
gl2 = game_line("CLE", "NYK", market_total=220.5)
table_row(["Metric", "Value"], header=True)
table_row(["TC Line", "**" + str(gl2["tc_line"]) + "**"])
table_row(["Market Total", "220.5"])
table_row(["Edge (vs Market)", str(gl2["edge"])])
table_row(["Signal", "**" + gl2["signal"] + "**"])
table_row(["CLE Starter TC", str(gl2["away_tc"])])
table_row(["NYK Starter TC", str(gl2["home_tc"])])
table_row(["Raw Combined (TC pts)", str(round(gl2["raw_combined"], 1))])
table_row(["TC Final (x1.52)", str(round(gl2["tc_final"], 1))])
p("")
p("**Note:** TC Line (208) is 12.5 points BELOW market total (220.5). " +
   "Both sides have edge — CLE starters slightly outperform NYK in TC model. " +
   "Signal is UNDER — market total is expensive.")
p("")

h2("TC System Summary — CLE @ NYK")
table_row(["Pick", "TC Line", "Market Total", "Edge", "Signal"], header=True)
sig2 = gl2["signal"]
pick2 = "UNDER" if sig2 == "UNDER" else "OVER"
table_row([pick2, str(gl2["tc_line"]), "220.5", str(gl2["edge"]), sig2])
p("")

player_table("CLE", "Cleveland Cavaliers", is_home=False)
player_table("NYK", "New York Knicks", is_home=True)

h2("Top Edge Bets — CLE @ NYK (Player Props)")
for pl in sorted(starters("CLE"), key=lambda x: abs(x.edge()), reverse=True)[:8]:
    e = pl.edge()
    conf = pl.conf() * 100
    pick = "OVER" if e > 0 else "UNDER"
    qual = "✅" if abs(e) >= 2.5 else "  "
    p("- " + qual + " **" + pl.name + "** (" + pl.pos + ") — "
      "TC_PTS: " + str(round(pl.tc_pts(), 1)) + " | Book Line: " + str(pl.book_line()) +
      " | Edge: **" + str(round(e, 1)) + "** | Conf: " + str(int(conf)) + "% | Pick: **" + pick + "**")

p("")
for pl in sorted(starters("NYK"), key=lambda x: abs(x.edge()), reverse=True)[:8]:
    e = pl.edge()
    conf = pl.conf() * 100
    pick = "OVER" if e > 0 else "UNDER"
    qual = "✅" if abs(e) >= 2.5 else "  "
    p("- " + qual + " **" + pl.name + "** (" + pl.pos + ") — "
      "TC_PTS: " + str(round(pl.tc_pts(), 1)) + " | Book Line: " + str(pl.book_line()) +
      " | Edge: **" + str(round(e, 1)) + "** | Conf: " + str(int(conf)) + "% | Pick: **" + pick + "**")

# ── BACKTEST AUDIT ───────────────────────────────────────────────────────────
divider()
h2("Backtest Audit — TC Engine v8.0 (Last 7 games)")
apply_injuries({"PHI": {"Joel Embiid": "OUT"}})
backtest_games = [
    ("2026-04-19", "BOS", "PHI", 214),
    ("2026-04-21", "BOS", "PHI", 208),
    ("2026-04-23", "BOS", "PHI", 208),
    ("2026-04-26", "BOS", "PHI", 224),
    ("2026-04-28", "PHI", "BOS", 208),
    ("2026-05-04", "MIN", "SA",  222),
    ("2026-05-06", "MIN", "SA",  215.5),
]
wins, losses = 0, 0
table_row(["Date", "Matchup", "Actual", "TC Line", "Signal", "Offset", "Result"], header=True)
for date, away, home, actual in backtest_games:
    gl = game_line(away, home, market_total=actual)
    tc = gl["tc_line"]
    sig = gl["signal"]
    off = actual - tc
    won = (sig == "UNDER" and actual < tc) or (sig == "OVER" and actual > tc)
    res = "✅ WIN" if won else "❌ LOSS"
    if won:
        wins += 1
    else:
        losses += 1
    table_row([date, away + "@" + home, str(actual), str(tc), sig, str(round(off, 1)), res])
table_row(["", "", "", "", "**Record**", "", str(wins) + "-" + str(losses) + " (" + str(int(wins/(wins+losses)*100)) + "%)"])

p("")
p("⚠️ **Backtest Warning:** 0-7 (0%) with PLAYOFF_MULT=1.52 — model appears to be **underestimating totals**. "
  "PLAYOFF_MULT may need recalibration. Recommend treating TC as a **relative comparison tool** across teams "
  "rather than an absolute line prediction.")
p("")

# ── FORMULA REFERENCE ─────────────────────────────────────────────────────────
divider()
h2("TC Formula Reference")
p("```")
p("Player TC  = stat * TC_W[stat] * INJ[status]")
p("TC_W       = {pts:0.85,  reb:0.80,  ast:0.75,  3pm:0.70}")
p("INJ        = {ACTIVE:1.00, QUESTIONABLE:0.55, OUT:0.00}")
p("")
p("Book Line (T) = floor(TC * 0.88)")
p("Edge     = TC - T   (positive = TC above book line -> OVER lean)")
p("")
p("Game TC   = (tc_start_A + tc_start_H) * PLAYOFF_MULT * 0.88")
p("PLAYOFF_MULT = 1.52 (calibrated from backtest but appears underestimated)")
p("")
p("Signal Logic:")
p("  TC_line < market_total -> UNDER (market total is expensive)")
p("  TC_line > market_total -> OVER  (market total is cheap)")
p("")
p("Betting Rules:")
p("  MIN_EDGE = 2.5 pts | MIN_CONF = 57%")
p("  OVER when TC > book line | UNDER when TC < book line")
p("  ⚠️ Backtest shows systematic underprediction — verify with live data")
p("```")
p("")
p("**TC Engine v8.0 | nba_tc_engine_v8.py**")

with open("/home/workspace/NBA_TC_Live_Report_May18_2026.md", "w") as f:
    f.write("\n".join(OUT))

print("Report written: /home/workspace/NBA_TC_Live_Report_May18_2026.md")